defmodule Voelgoedevents.Repo.Migrations.AddFinanceAndAccessControl do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:ledgers, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :amount, :map
    end

    create table(:api_keys, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key_hash, :text, null: false
    end
  end

  def down do
    drop table(:api_keys)

    drop table(:ledgers)
  end
end
