defmodule Voelgoedevents.Ash.Resources.AccessControl.ApiKey do
  @moduledoc """
  RESOURCE: ApiKey
  Represents a machine-to-machine credential linked to a specific Tenant.
  """
  use Ash.Resource,
    domain: Voelgoedevents.Ash.Domains.AccessControlDomain,
    data_layer: AshPostgres.DataLayer,
    # ✅ KEPT YOUR EXTENSIONS (Good security practice)
    extensions: [AshCloak, AshArchival]

  postgres do
    table "api_keys"
    repo Voelgoedevents.Repo
  end

  attributes do
    uuid_primary_key :id

    # ✅ ADDED: Friendly name for the key (e.g. "Zapier Integration")
    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :key_hash, :string do
      allow_nil? false
      sensitive? true
    end

    # ✅ ADDED: Critical Link to Tenant
    attribute :organization_id, :uuid, allow_nil?: false

    # ✅ ADDED: Scope permissions (e.g. ["read:events", "write:tickets"])
    attribute :permissions, {:array, :string} do
      public? true
      default []
    end

    timestamps()
  end

  # ✅ ADDED: Relationship to Tenant
  relationships do
    belongs_to :organization, Voelgoedevents.Ash.Resources.Accounts.Organization
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      # We accept name/org, but key_hash will be generated by logic later
      accept [:name, :organization_id, :permissions]
    end
    
    update :update do
      accept [:name, :permissions]
    end
  end
end