defmodule Voelgoedevents.Ash.Resources.AccessControl.ApiKey do
  @moduledoc """
  RESOURCE: ApiKey
  Represents a machine-to-machine credential linked to a specific Tenant.
  """
  use Voelgoedevents.Ash.Resources.Base,
    domain: Voelgoedevents.Ash.Domains.AccessControlDomain,
    # ✅ KEPT YOUR EXTENSIONS (Good security practice)
    extensions: [AshCloak, AshArchival]

  alias Voelgoedevents.Ash.Policies.PlatformPolicy

  require PlatformPolicy

  postgres do
    table "api_keys"
    repo Voelgoedevents.Repo
  end

  attributes do
    uuid_primary_key :id

    # ✅ ADDED: Friendly name for the key (e.g. "Zapier Integration")
    attribute :name, :string do
      allow_nil? false
      public? true
    end

    attribute :key_hash, :string do
      allow_nil? false
      sensitive? true
    end

    # ✅ ADDED: Critical Link to Tenant
    attribute :organization_id, :uuid, allow_nil?: false

    # ✅ ADDED: Scope permissions (e.g. ["read:events", "write:tickets"])
    attribute :permissions, {:array, :string} do
      public? true
      default []
    end

    timestamps()
  end

  # ✅ ADDED: Relationship to Tenant
  relationships do
    belongs_to :organization, Voelgoedevents.Ash.Resources.Accounts.Organization
  end

  policies do
    PlatformPolicy.platform_admin_root_access()

    # Read actions: Allow if actor belongs to same organization
    policy action_type(:read) do
      forbid_if expr(is_nil(^actor(:user_id)))

      authorize_if expr(
                     organization_id == ^actor(:organization_id) and
                       ^actor(:role) in [:owner, :admin]
                   )
    end

    # Create actions: Only owners and admins can create API keys
    # Must create within their own organization
    policy action_type(:create) do
      forbid_if expr(is_nil(^actor(:user_id)))

      authorize_if expr(
                     arg(:organization_id) == ^actor(:organization_id) and
                       ^actor(:role) in [:owner, :admin]
                   )
    end

    # Update actions: Only owners and admins can update API keys
    # Must be within their own organization
    policy action_type(:update) do
      forbid_if expr(is_nil(^actor(:user_id)))

      authorize_if expr(
                     organization_id == ^actor(:organization_id) and
                       ^actor(:role) in [:owner, :admin]
                   )
    end

    # Destroy actions: Only owners and admins can destroy API keys
    # Must be within their own organization
    policy action_type(:destroy) do
      forbid_if expr(is_nil(^actor(:user_id)))

      authorize_if expr(
                     organization_id == ^actor(:organization_id) and
                       ^actor(:role) in [:owner, :admin]
                   )
    end
  end

  actions do
    defaults [:read, :destroy]

    create :create do
      primary? true
      # We accept name/org, but key_hash will be generated by logic later
      accept [:name, :organization_id, :permissions]
    end

    update :update do
      accept [:name, :permissions]
    end
  end
end
